### ISSUE TITLE
重复做题,感觉需要一个重置代码区的功能

### ISSUE THREAD

**Issue by ccagml** [ccagml/leetcode-vscode#124]

**Comment by CTCSU** [comment]
@ccagml 或者可不可以加一个file parameter，加一个${yyyymmdd} 的参数，生成的文件中Solution 就会是空的。

这样根据文件名还可以做统计。

**Comment by ccagml** [comment]
@CTCSU 感谢

**Comment by simitsu** [comment]
所以应该要如何操作呢？
