### ISSUE TITLE
现在为啥不可以在直接在tag中筛选分数区间了

### ISSUE THREAD

**Issue by 98zyx** [ccagml/leetcode-vscode#148]
之前可以在选择分数区间之后，相应tag中也会只有指定分数区间的题目，现在为啥没有这个功能了...这个功能很好用呀

**Comment by ccagml** [comment]
有的吧，Leetcode-problem-rating: Hide Score配置选择ScoreRange，
注意下Leetcode-problem-rating: Pick One By Rank Range Max
Leetcode-problem-rating: Pick One By Rank Range Min
的分数范围

**Comment by ccagml** [comment]
选完没用的话，点刷新看看有没有用
