### ISSUE TITLE
测试用例块中的字符串用例上传时会丢失其中的井号字符（`#`）

### ISSUE THREAD

**Issue by lewis-yeung** [ccagml/leetcode-vscode#151]
点击测试用例块（`@lcpr case`）中的 `case` 运行测试时，若用例为含有若干 `#` 的字符串，则会导致最终上传的用例中所有 `#` 都会丢失。暂时只在 C++ 中发现该问题（如下图所示），其他语言未测试。若点击 `Test` 直接手动输入用例并测试，则没有该问题。

![bug_1](https://user-images.githubusercontent.com/83903009/213903203-81d06eec-faf4-45fa-808c-71ca8820cef5.png)
![bug_2](https://user-images.githubusercontent.com/83903009/213903204-91b1edfd-dead-4937-9b04-861c1590e906.png)

相关日志：

```json
{"messages":["Finished"],"system_message":{"fid":"844","id":874,"qid":874,"sub_type":"test","accepted":true},"Your Input":["\"acd\"\n\"abad\"\n"],"Output (4 ms)":["false"],"Expected Answer":["false"],"Stdout":[""]}
```

**Comment by ccagml** [comment]
已修复,感谢
