### ISSUE TITLE
初次启动的时候删除缓存

### ISSUE THREAD

**Issue by JiaoZiLang** [ccagml/leetcode-vscode#166]
# 建议措施
首次App的打开插件的时候，应该每次都会去拉取已经做过的题目，这个时候可以覆盖一下这个缓存
```
.lcpr/leetcode/cache/problems.json
```
# 需求背景
经常活跃于不同PC 电脑的该插件刷，经常发现问题不同步问题。
## 早期
点击删除缓存，然后每次都要 **重新登陆**
## 后期
找到缓存的文件，手动删除，再重新打开插件

# 个人观点
cache 在于加速和减轻压力，但是不应该导致不一致问题，发现每次打开App插件的时候会主动拉一次解决题目了，这个时候建议覆盖cache；或者判断cache的文件创建时间如果少于 xx 时间，则直接复用；每次启动插件的时候更新一把cache 还是有必要的。

**Comment by ccagml** [comment]
2.13.2加了两个设置
openClearProblemCache
openClearProblemCacheTime
